apiVersion: v1
kind: Service
metadata:
    name: postgres-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        compoenent: postgres
    ports:
        - port: 5432        # Inside the cluster, the service is visible via this port
          targetPort: 5432  # Which port do pods selected by this service expose?