apiVersion: v1
kind: Service
metadata:
    name: redis-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        compoenent: redis
    ports:
        - port: 6379        # Inside the cluster, the service is visible via this port
          targetPort: 6379  # Which port do pods selected by this service expose?